name: dkd
description: Universal Message Module (Dao-Ke-Dao).
version: 1.2.2
homepage: https://github.com/dimchat/dkd-dart
repository: https://github.com/dimchat/dkd-dart
issue_tracker: https://github.com/dimchat/dkd-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  mkm: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
