name: dkd
description: Universal Message Module (Dao-Ke-Dao).
version: 0.1.0-dev.5
homepage: https://github.com/dimchat/dkd-dart
repository: https://github.com/dimchat/dkd-dart
issue_tracker: https://github.com/dimchat/dkd-dart/issues

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

# Add regular dependencies here.
dependencies:
  mkm: ^0.1.0-dev.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
