/* license: https://mit-license.org
 *
 *  Dao-Ke-Dao: Universal Message Module
 *
 *                                Written in 2023 by Moky <albert.moky@gmail.com>
 *
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2023 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
import 'package:mkm/format.dart';

import 'helpers.dart';
import 'secure.dart';

///  Reliable Message signed by an asymmetric key
///  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
///  This class is used to sign the SecureMessage
///  It contains a 'signature' field which signed with sender's private key
///
///  data format: {
///      //-- envelope
///      "sender"   : "moki@xxx",
///      "receiver" : "hulk@yyy",
///      "time"     : 123,
///
///      //-- content data and key/keys
///      "data"     : "...",  // base64_encode( symmetric_encrypt(content))
///      "keys"     : {
///          "{ID}"   : "...",  // base64_encode(asymmetric_encrypt(pwd))
///          "digest" : "..."   // hash(pwd.data)
///      },
///      //-- signature
///      "signature": "..."   // base64_encode(asymmetric_sign(data))
///  }

/// Interface for signed reliable messages (third/final stage).
///
/// Extends [SecureMessage] with a digital signature generated by the sender's
/// private key, providing both confidentiality (from encryption) and authenticity/
/// integrity (from signing). This is the final stage of message transformation
/// for secure transmission.
///
/// Serialized format (Map/JSON):
/// ```json
/// {
///   // Envelope metadata (unchanged from previous stages)
///   "sender": "moki@xxx",      // Sender's unique ID
///   "receiver": "hulk@yyy",    // Receiver's unique ID
///   "time": 123,               // Message timestamp (Unix timestamp in seconds)
///
///   // Encrypted content and keys (from SecureMessage)
///   "data": "...",             // base64_encode( symmetric_encrypt(content))
///   "keys": {
///     "{RecipientID}": "...",  // base64_encode(asymmetric_encrypt(pwd))
///     "digest": "..."          // hash(pwd.data)
///   },
///   // Digital signature (new for ReliableMessage)
///   "signature": "..."         // Base64-encoded signature (signed with sender's private key)
/// }
/// ```
abstract interface class ReliableMessage implements SecureMessage {

  /// Digital signature of the encrypted [data] field.
  ///
  /// Generated by signing the [data] (encrypted content) with the sender's private key
  /// (asymmetric signing). This signature verifies the message's authenticity (sender
  /// is who they claim to be) and integrity (message hasn't been tampered with).
  /// Wrapped in [TransportableData] for standardized encoding/transmission.
  /// Cannot be null (core security feature of reliable messages).
  TransportableData get signature;

  //
  //  Conveniences
  //

  static List<ReliableMessage> convert(Iterable array) {
    List<ReliableMessage> messages = [];
    ReliableMessage? msg;
    for (var item in array) {
      msg = parse(item);
      if (msg == null) {
        continue;
      }
      messages.add(msg);
    }
    return messages;
  }

  static List<Map> revert(Iterable<ReliableMessage> messages) {
    List<Map> array = [];
    for (ReliableMessage msg in messages) {
      array.add(msg.toMap());
    }
    return array;
  }

  //
  //  Factory methods
  //

  static ReliableMessage? parse(Object? msg) {
    var ext = MessageExtensions();
    return ext.reliableHelper!.parseReliableMessage(msg);
  }

  static ReliableMessageFactory? getFactory() {
    var ext = MessageExtensions();
    return ext.reliableHelper!.getReliableMessageFactory();
  }
  static void setFactory(ReliableMessageFactory factory) {
    var ext = MessageExtensions();
    ext.reliableHelper!.setReliableMessageFactory(factory);
  }
}


/// Factory interface for parsing [ReliableMessage] instances from serialized data.
///
/// Provides a method to reconstruct reliable messages from their serialized Map/JSON
/// representation, with validation of both encrypted data and digital signature.
abstract interface class ReliableMessageFactory {

  /// Parses a serialized Map into a [ReliableMessage] instance.
  ///
  /// Validates the structure (required fields: data, keys, signature) and converts
  /// raw values (e.g., Base64 string → TransportableData for signature) to proper types.
  ///
  /// [msg]: Serialized reliable message data (matches format in [ReliableMessage])
  ///
  /// Returns: [ReliableMessage] instance if parsing succeeds, null otherwise
  ReliableMessage? parseReliableMessage(Map msg);
}
