/* license: https://mit-license.org
 *
 *  Dao-Ke-Dao: Universal Message Module
 *
 *                                Written in 2023 by Moky <albert.moky@gmail.com>
 *
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2023 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
import 'package:mkm/format.dart';

import 'envelope.dart';
import 'helpers.dart';


/// Interface for encrypted secure messages (second stage).
///
/// Represents an [InstantMessage] that has been encrypted with a symmetric key,
/// providing confidentiality for the message content. The original plaintext
/// content is replaced with encrypted data and encrypted keys for decryption.
///
/// Serialized format (Map/JSON):
/// ```json
/// {
///   // Envelope metadata (unchanged from InstantMessage)
///   "sender": "moki@xxx",      // Sender's unique ID
///   "receiver": "hulk@yyy",    // Receiver's unique ID
///   "time": 123,               // Message timestamp (Unix timestamp in seconds)
///
///   // Encrypted content and keys
///   "data": "...",             // base64_encode( symmetric_encrypt(content))
///   "keys": {
///     "{RecipientID}": "...",  // base64_encode(asymmetric_encrypt(pwd))
///     "digest": "..."          // hash(pwd.data)
///   }
/// }
/// ```
abstract interface class SecureMessage implements Message {

  /// Encrypted message content (Base64-encoded).
  ///
  /// Generated by encrypting the [InstantMessage.content] with a symmetric key
  /// (e.g., AES). Wrapped in [TransportableData] for standardized encoding/transmission.
  /// Cannot be null (core payload of the secure message).
  TransportableData get data;

  /// Map of encrypted symmetric keys (recipient ID → encrypted key string).
  ///
  /// Each entry contains a symmetric key encrypted with the recipient's public key
  /// (asymmetric encryption), ensuring only the intended recipient can decrypt it.
  /// The "digest" entry contains a hash of the raw symmetric key for verification.
  ///
  /// Returns: Map of encrypted keys, or null if no keys are present (uncommon)
  Map? get encryptedKeys;  // String => String

  //
  //  Factory methods
  //

  static SecureMessage? parse(Object? msg) {
    var ext = MessageExtensions();
    return ext.secureHelper!.parseSecureMessage(msg);
  }

  static SecureMessageFactory? getFactory() {
    var ext = MessageExtensions();
    return ext.secureHelper!.getSecureMessageFactory();
  }
  static void setFactory(SecureMessageFactory factory) {
    var ext = MessageExtensions();
    ext.secureHelper!.setSecureMessageFactory(factory);
  }
}


/// Factory interface for parsing [SecureMessage] instances from serialized data.
///
/// Provides a method to reconstruct secure messages from their serialized Map/JSON
/// representation, with proper validation of encrypted data and keys.
abstract interface class SecureMessageFactory {

  /// Parses a serialized Map into a [SecureMessage] instance.
  ///
  /// Validates the structure (required fields: sender, receiver, data) and converts
  /// raw values (e.g., Base64 string → TransportableData) to proper types.
  ///
  /// [msg]: Serialized secure message data (matches format in [SecureMessage])
  ///
  /// Returns: [SecureMessage] instance if parsing succeeds, null otherwise
  SecureMessage? parseSecureMessage(Map msg);
}
